### ISSUE TITLE
Warnings concerning file ownerships

### ISSUE THREAD

**Issue by ghigad** [digrouz/docker-ddclient#2]
Hi,

I'm trying to using your Docker container for ddclient.  Everything seems to work fine so far, except for one thing.

I have the following warnings in the log files:

```
WARNING:  file /etc/ddclient/ddclient.conf: file /etc/ddclient/ddclient.conf should be owned only by ddclient or not be writable.
WARNING:  file /etc/ddclient/ddclient.conf: file /etc/ddclient/ddclient.conf should be owned only by ddclient or not be writable.
WARNING:  file /var/cache/ddclient/cache/ddclient/ddclient.cache: file /var/cache/ddclient/cache/ddclient/ddclient.cache should be owned only by ddclient or not be writable.
```

I think this could be easily solved by having a user `ddclient` and a group `ddclient` and by running `ddclient` using this user.

Also, I think that file ownerships should be updated from `appuser` (UID 12345) to `ddclient`.

This would remove these annoying messages in the logs.

Thank you for your help!

Best regards!

**Comment by digrouz** [comment]
Hello,

Can you share a bit of context: 
- how you are deploying my image ? 
- Are you using volumes ?
- Can you share the general section of your ddclient.conf file ? (not interest into the domain specific parts of course)

Kind regards

Nicolas

**Comment by digrouz** [comment]
I pushed some file permissions fixes.

But i don't get why you are getting warning about ddclient user. Please share some extra informations so I better help :)

**Comment by ghigad** [comment]
Hi!

Thank you for the quick feedback.

I don't have access to my environment right now, but I will gladly share the information as soon as I can.

Best regards!

**Comment by ghigad** [comment]
Hi!

Here is the info you requested...

First, my ddclient.conf...
```
protocol=freedns
syslog=yes
mail=<mail address>
mail-failure=<mail address>
ssl=yes
use=web
web=freedns
server=freedns.afraid.org
login=<login>
password='<password>'
<mydomainname>
```

I use Docker Compose to start the container.  Here is my `compose.yml` file...

```yml
version: "3"
services:
  ddclient:
    image: digrouz/ddclient:latest
    container_name: ddclient
    hostname: ddclient
    environment:
      - DOCKMAIL=<mail address>
      - DOCKRELAY=<my relay>
      - DOCKMAILDOMAIN=<my domain>
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/ddclient.conf:/etc/ddclient/ddclient.conf
    restart: unless-stopped
```

I start my container with `docker compose up -d`.

If I attach to my container (`docker exec -ti ddclient sh`) and run `/opt/ddclient/ddclient`, I get the warnings mentionned in my original message.

Thanks again for your help!

Best regards!
